# Generated by Django 6.1.1 on 2026-09-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('progress', models.FloatField(default=0.0)),
                ('message', models.TextField(blank=True, default='')),
                ('results', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('module', models.CharField(max_length=32)),
                ('level', models.CharField(default='INFO', max_length=8)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
    ]
